#!/bin/bash

# Declare variable choice and assign value 99
choice=99
# Print to stdout
 echo "1) Update System"
 echo "2. Ad Blocker"
 echo "3 Twitter Bot"
 echo "4. Minecraft Server"
 echo -n "Please choose a number? "
# Loop while the variable choice is equal 99
# bash while loop
while [ $choice -eq 99 ]; do

# read user input
read choice
# bash nested if/else

 if [ $choice -eq 1 ] ; then
  sh scripts/update

else if [ $choice -eq 2 ] ; then
  sh scripts/ad-blocker

else if [ $choice -eq 3 ] ; then
  sh scripts/twitter-bot

  else if [ $choice -eq 4 ] ; then
    sh scripts/minecraft-server

# If something else is selected, Show the choice options again
        else
       echo "Please make a choice between 1-3 !"
       echo "1. Bash"
       echo "2. Scripting"
       echo "3. Tutorial"
       echo -n "Please choose a word [1,2 or 3]? "
        choice=99
           fi
        fi
fi
done
