#!/bin/bash

# Declare variable choice and assign value 99
choice=99
# Print to stdout
 echo "1) Update System"
 echo "2. Ad Blocker"
 echo "3 Twitter Bot"
 echo "4. Minecraft Client"
 echo "5. Minecraft Server"
 echo "6. Home Assistant"
 echo "7. Amazon Alexa"
 echo "8. Tor"
 echo -n "Please choose a number? "
# Loop while the variable choice is equal 99
 #bash while loop
while [ $choice -eq 99 ]; do

# read user input
read choice
# bash nested if/else

 if [ $choice -eq 1 ] ; then
  cd project_scripts
  sh update

else if [ $choice -eq 2 ] ; then
  cd project_scripts
  sh ad-blocker

else if [ $choice -eq 3 ] ; then
  cd project_scripts
  sh stwitter-bot

else if [ $choice -eq 4 ] ; then
  cd project_scripts
  sh minecraft-client

else if [ $choice -eg 5 ] ; then
  cd project_scripts
  sh minecraft-server

else if [ $choice -eq 6 ] ; then
  cd project_scripts
  sh home-assistant

else if [ $choice -eq 7 ] ; then
  cd project_scripts
  sh amazon-alexa

else if [ $choice -eq 8 ] ; then
  cd project_scripts
  sh tor


# If something else is selected, Show the choice options again
        else
          echo "1) Update System"
          echo "2. Ad Blocker"
          echo "3 Twitter Bot"
          echo "4. Minecraft Client"
          echo "5. Minecraft Server"
          echo "6. Home Assistant".
          echo "7.. Amazon Alexa"
       echo -n "Please choose a number? "
        choice=99
           fi
        fi
fi
fi
fi
fi
fi
done
