#!/bin/bash

echo "This script is still under development"
echo "installing Tor"
sudo apt-get install tor -y
echo "make the following changes in the file below"
echo "Log notice file /var/log/tor/notices.log
VirtualAddrNetwork 10.192.0.0/10
AutomapHostsSuffixes .onion,.exit
AutomapHostsOnResolve 1
TransPort 9040
TransListenAddress 192.168.220.1
DNSPort 53
DNSListenAddress 192.168.220.1"
sudo nano /etc/tor/torrc
echo "fluching the iptables"
sudo iptables -F
sudo iptables -t nat -F
echo "installing new iptables"
sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 22 -j REDIRECT --to-ports 22
sudo iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 53 -j REDIRECT --to-ports 53
sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --syn -j REDIRECT --to-ports 9040
echo "check if the iptables have been installed"
sudo iptables -t nat -L
echo "stroing the file"
sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
echo "create a log file"
sudo touch /var/log/tor/notices.log
sudo chown debian-tor /var/log/tor/notices.log
sudo chmod 644 /var/log/tor/notices.log
echo "check log and perms"
ls -l /var/log/tor
sudo service tor start
sudo service tor status
sudo update-rc.d tor enable

echo "Tor has been installed"
