#!/bin/bash

echo "Installing Twitter Bot"
cd /home/pi/projects
mkdir Twitter_Bot
cd Twitter_Bot
sudo apt-get install npm -y
npm init
npm install --save twit request
echo "you can now add the files here"
echo "Twitter bot has been installed"
